### ISSUE TITLE
gradle and spring boot plugin and errors with docker java

### ISSUE THREAD

**Issue by vbasem** [bmuschko/gradle-docker-plugin#467]
thanks alot for the great plugin. 
we have sadly encountered a strange issue with the docker java plugin ever since we upgraded to spring boot M4.

```
Execution failed for task ':mrm-external_ota:buildImage'.
> Could not resolve all dependencies for configuration ':mrm-external_ota:dockerJava'.
   > Could not determine artifacts for javax.ws.rs:javax.ws.rs-api:2.1
      > Could not get resource 'https://[internalrep]/repository/maven-central/javax/ws/rs/javax.ws.rs-api/2.1/javax.ws.rs-api-2.1.$%7Bpackaging.type%7D'.
         > Could not HEAD 'https://[internalrep]/repository/maven-central/javax/ws/rs/javax.ws.rs-api/2.1/javax.ws.rs-api-2.1.$%7Bpackaging.type%7D'. Received status code 500 from server: Server Error
```

while I have no problem resolving and building the project, it fails while fetching the deps during docker image builds and as I see it ```$%7Bpackaging.type%7D``` is not replaced correctly which should be the package type variable.

If I switch back to spring boot M3 plugin, this will run as well, so not sure whats going on!

Any ideas ?

**Comment by gnilron** [comment]
I have similar issues with Springboot 2.0M4

Seems to be related to jersey and a new version with Springboot 2.0M4, not sure why that causes it. 

I get this stacktrace with M4 but M3 works fine
`
[dockerjava-jaxrs-async-0] ERROR com.github.dockerjava.core.async.ResultCallbackTemplate - Error during callback
java.lang.IllegalStateException: InjectionManagerFactory not found.
	at org.glassfish.jersey.internal.inject.Injections.lambda$lookupInjectionManagerFactory$0(Injections.java:98)
`

**Comment by orzeh** [comment]
@vbasem  @gnilron this seems to be two different issues. Could you both provide minimal build script which reproduces them?

**Comment by orzeh** [comment]
I've just created small Spring Boot M.4 application and was able to build a Docker image without any issues.

**Comment by cdancy** [comment]
This all sounds like typical classpath issues due to older/newer libs on the path. I opened an ISSUE with the docker-java guys to get a shaded version of their plug-in but that seems to have stalled.

@orzeh we could build and publish our own. I really don't want to maintain that but maybe there is a solution here which we could work with. IDK.

**Comment by vbasem** [comment]
as much as it shames to say this, I am not able to reproduce this on a simple project as I get stuck around @gnilron issue. 
My original project would be too complex to rebuild, so I guess I can only proceed when the injection problem is solved. I have a feeling that will bring me further as well.

**Comment by nikolaidueck** [comment]
It looks like spring boot version 2.0.0.M4 uses a newer version of the jersey client.
@orzeh you need to add the new version to your buildscript dependency:
```
buildscript {
	ext {
		springBootVersion = "2.0.0.M4"
	}

	repositories {
		maven { url "https://repo.spring.io/plugins-snapshot" }
		maven { url "https://plugins.gradle.org/m2/" }
	}

	dependencies {
		classpath "org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}"
	}
}
```

**Comment by gnilron** [comment]
@nikolaidueck Yes, but I need the docker plugin also. Like this:

`    dependencies {
        classpath 'com.bmuschko:gradle-docker-plugin:3.1.0' //  I want older jersey
        classpath 'com.avast.gradle:docker-compose-gradle-plugin:0.5.0'
        classpath 'org.springframework.boot:spring-boot-gradle-plugin:2.0.0.M4' // I want the new jersey
        // classpath 'org.springframework.boot:spring-boot-gradle-plugin:2.0.0.M3' // I play nice with old jersey
    }
`

**Comment by orzeh** [comment]
OK, my mistake, now I'm able to reproduce @gnilron issue. However, I have no idea how to fix this. Basically it's a Gradle issue as plugins share build classpath. `docker-java` can upgrade jersey version but it's a temporary solution. Any other ideas?

**Comment by titoc** [comment]
Confirming the same issue as @gnilron .  With  `com.bmuschko:gradle-docker-plugin:3.0.11` and `springBootVersion = '2.0.0.M4'`

```
11:52:33.721 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Caused by: java.lang.IllegalStateException: InjectionManagerFactory not found.
11:52:33.721 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.glassfish.jersey.internal.inject.Injections.lambda$lookupInjectionManagerFactory$0(Injections.java:98)
11:52:33.721 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.glassfish.jersey.internal.inject.Injections.lookupInjectionManagerFactory(Injections.java:98)
11:52:33.721 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.glassfish.jersey.internal.inject.Injections.createInjectionManager(Injections.java:68)
11:52:33.721 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.glassfish.jersey.client.ClientConfig$State.initRuntime(ClientConfig.java:432)
11:52:33.721 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.glassfish.jersey.internal.util.collection.Values$LazyValueImpl.get(Values.java:341)
11:52:33.721 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.glassfish.jersey.client.ClientConfig.getRuntime(ClientConfig.java:826)
11:52:33.721 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.glassfish.jersey.client.ClientRequest.getConfiguration(ClientRequest.java:285)
11:52:33.721 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.glassfish.jersey.client.JerseyInvocation.validateHttpMethodAndEntity(JerseyInvocation.java:143)
11:52:33.721 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.glassfish.jersey.client.JerseyInvocation.<init>(JerseyInvocation.java:112)
11:52:33.721 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.glassfish.jersey.client.JerseyInvocation.<init>(JerseyInvocation.java:108)
11:52:33.721 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.glassfish.jersey.client.JerseyInvocation.<init>(JerseyInvocation.java:99)
11:52:33.722 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:456)
11:52:33.722 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:357)
11:52:33.722 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.github.dockerjava.jaxrs.async.POSTCallbackNotifier.response(POSTCallbackNotifier.java:29)
11:52:33.722 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.github.dockerjava.jaxrs.async.AbstractCallbackNotifier.call(AbstractCallbackNotifier.java:50)
11:52:33.722 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.github.dockerjava.jaxrs.async.AbstractCallbackNotifier.call(AbstractCallbackNotifier.java:24)
```

**Comment by wwadge** [comment]
There's already a shaded version of docker-java published. This patch will make it work:
```
diff --git a/src/main/groovy/com/bmuschko/gradle/docker/DockerRemoteApiPlugin.groovy b/src/main/groovy/com/bmuschko/gradle/docker/DockerRemoteApiPlugin.groovy
index c5431d8..506d89e 100644
--- a/src/main/groovy/com/bmuschko/gradle/docker/DockerRemoteApiPlugin.groovy
+++ b/src/main/groovy/com/bmuschko/gradle/docker/DockerRemoteApiPlugin.groovy
@@ -50,7 +50,7 @@ class DockerRemoteApiPlugin implements Plugin<Project> {
 
         Configuration config = project.configurations[DOCKER_JAVA_CONFIGURATION_NAME]
         config.defaultDependencies { dependencies ->
-            dependencies.add(project.dependencies.create("com.github.docker-java:docker-java:$DockerRemoteApiPlugin.DOCKER_JAVA_DEFAULT_VERSION"))
+            dependencies.add(project.dependencies.create("com.nirima:gradle-docker-plugin:0.16.2"))
             dependencies.add(project.dependencies.create('org.slf4j:slf4j-simple:1.7.5'))
             dependencies.add(project.dependencies.create('cglib:cglib:3.2.0'))
         }
 
```

From here: https://github.com/jenkinsci/docker-plugin/blob/master/docker-java-shaded/pom.xml

Can we use this version instead?

**Comment by orzeh** [comment]
@wwadge This library doesn't shade Jersey, so I doubt it will help.

BTW everyone can try it just by excluding `docker-java` from configuration created by this plugin (which is named `dockerJava`) and adding other libs.

**Comment by wwadge** [comment]
Hi @orzeh can you give us an example how to do this please?

**Comment by wwadge** [comment]
for the example before I meant:
     dependencies.add(project.dependencies.create("com.nirima:docker-java-shaded:0.16.2"))

**Comment by orzeh** [comment]
@wwadge I created repository with example: https://github.com/orzeh/gradle-docker-plugin-spring-boot-m4

It builds image, so issue reported here is fixed, however it seems that this shaded library is out of date, because build fails with: 

````console
orzeh@dell:~/gradle-docker-plugin-spring-boot-m4$ gradle buildImage -S
Step 1/2 : FROM alpine
---> 7328f6f8b418
Step 2/2 : RUN ps -a
---> Using cache
---> 9f2f8641b4d4
Successfully built 9f2f8641b4d4
Successfully tagged spring-boot-app:0.0.1-SNAPSHOT

> Task :buildImage
Building image using context 'gradle-docker-plugin-spring-boot-m4'.
Using tag 'spring-boot-app:0.0.1-SNAPSHOT' for image.


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':buildImage'.
> Could not build image: null
````
This seems to be [this issue](https://github.com/docker-java/docker-java/issues/830) in `docker-java`

**Comment by gnilron** [comment]
@orzeh I'm getting the same issue in my project testing that workaround.
What do you think is the way forward? Try to get an updated shaded jar?

**Comment by cdancy** [comment]
@gnilron I would reach out and try to get an updated shaded jar if that's what works for you. You could always hop on the [docker-java gitter](https://gitter.im/docker-java/docker-java) channel and bug those guys about providing one OOTB as I've done as much many times myself :)

**Comment by awesometown** [comment]
I had previously worked-around the "Could not build image: null" by having separate "buildImage" and "tagImage" tasks as suggested in https://github.com/bmuschko/gradle-docker-plugin/issues/399. Leaving off the `tag` property in the `buildImage` seems to be key.

```
task buildImage(type: DockerBuildImage, group: 'docker') {
	dependsOn copyDockerfileForDocker, copyJarForDocker
	inputDir = file('build/dockerAssemble')
}

task tagImageLatest(type: DockerTagImage) {
	dependsOn buildImage
	targetImageId { buildImage.getImageId() }
	repository = "mydockerimage"
	tag = "latest"
}
```
That, in conjunction with the changes in the linked repository from @orzeh above seems to have allowed me to build and dockerize a Spring Boot 2.0 application (`2.0.0.M5` specifically).

**Comment by rafalQA** [comment]
Hi. Currently I use Spring Boot 2.0.0.BUILD-SNAPSHOT with  com.bmuschko:gradle-docker-plugin: 3.2.1. I still get
Using tag 'sampleName' for image
`[dockerjava-jaxrs-async-0] ERROR com.github.dockerjava.core.async.ResultCallbackTemplate - Error during callback
java.lang.IllegalStateException: InjectionManagerFactory not found.
`
Is not clear for me. There is plan to repair it or maybe some workaround is for now ?
If about this https://github.com/orzeh/gradle-docker-plugin-spring-boot-m4
It get me error when I write  "docker java".

I'm new in gradle. Please for advice.

**Comment by takuro-yamane** [comment]
```groovy
repositories {
    maven { url 'https://oss.sonatype.org/content/groups/public' }
}

dependencies {
    dockerJava 'com.github.docker-java:docker-java:3.1.0-SNAPSHOT'
    dockerJava 'org.slf4j:slf4j-simple:1.7.5'
    dockerJava 'cglib:cglib:3.2.0'
}
```
https://github.com/takuro-yamane/gradle-docker-plugin-spring-boot-m4

**Comment by orzeh** [comment]
@rafalQA please check @takuro-yamane example - it seems to work.

@takuro-yamane thanks for sharing this! I checked and it works well with latest M7 too :+1:

**Comment by iNikem** [comment]
Any plans of fixing this issue?

**Comment by orzeh** [comment]
@iNikem we will probably wait until SB 2.0 is released. That being said we may not be able to fix it without changes in `docker-java`.

**Comment by n0mer** [comment]
for me spring-boot RC1 worked with the following in dependencyManagement section:

```groovy
        dependency 'javax.ws.rs:javax.ws.rs-api:2.1'
        dependency 'com.github.docker-java:docker-java:3.1.0-SNAPSHOT'
```

**Comment by cdancy** [comment]
If we could just get `docker-java` to publish a shaded/uber version of their library we could side-step this issue but my plea for them to do that falls on deaf ears. We could always switch to using spotify's `docker-client` which seems to be gaining traction recently...

**Comment by hanswesterbeek** [comment]
Bumped into this issue today as well. More will come as Spring Boot is now at RC2. It won't be long until the masses come :)

**Comment by cdancy** [comment]
I'm going to put together a PR this weekend to load all client jars in their own classloader much like we are doing with the [gradle-kubernetes-plugin](https://github.com/bmuschko/gradle-kubernetes-plugin/blob/master/src/main/groovy/com/bmuschko/gradle/kubernetes/plugin/GradleKubernetesContextLoader.groovy#L74). This _should_ provide the final solution here and allow folks to put whatever they want on any classpath without clobbering going on.

**Comment by cdancy** [comment]
@orzeh put together a project solely for the purpose of building a shaded version of `docker-java` which I will maintain and publish to jcenter. My thinking is to use this, in place of depending on `docker-java`, which should get us around issues like this once and for all. As the `docker-java` project itself seems to not want to do the work I went ahead and knocked it out. Give it a look over and let me know what you think of the idea.

https://github.com/project-aries/docker-java-shaded

**Comment by cdancy** [comment]
New version of plugin `3.2.5` resolves these types of issues. Anyone on an older version is asked to please upgrade lest you enjoy the pain.

**Comment by abansod** [comment]
@cdancy I upgraded to latest version `3.2.5`, getting below error - 
```
Could not resolve all files for configuration ':dockerJava'.
   > Could not find com.aries:docker-java-shaded:3.0.14.
     Searched in the following locations:
         file:/Users/akshaybansod/.m2/repository/com/aries/docker-java-shaded/3.0.14/docker-java-shaded-3.0.14.pom
         file:/Users/akshaybansod/.m2/repository/com/aries/docker-java-shaded/3.0.14/docker-java-shaded-3.0.14.jar
         https://repo1.maven.org/maven2/com/aries/docker-java-shaded/3.0.14/docker-java-shaded-3.0.14.pom
         https://repo1.maven.org/maven2/com/aries/docker-java-shaded/3.0.14/docker-java-shaded-3.0.14.jar
         http://maven.twttr.com/com/aries/docker-java-shaded/3.0.14/docker-java-shaded-3.0.14.pom
         http://maven.twttr.com/com/aries/docker-java-shaded/3.0.14/docker-java-shaded-3.0.14.jar
```

**Comment by cdancy** [comment]
@abansod is that really your config? The output suggests its not reaching jcenter because it's not defined. You normally define plugins on the buildscript config and not the project config.

**Comment by abansod** [comment]
@cdancy I have created a wrapper plugin using `com.bmuschko:gradle-docker-plugin:3.2.5`.

**Comment by cdancy** [comment]
@abansod as I don't know what that looks like I can't be of further help but I do know from the ouput above that the repos you defined in that snippet are NOT the repos that are being used. If I had to venture a guess I would say you have mavenLocal, mavenCentral, and some Twitter repo defined. Wherever that code is you need to add a jcenter repo as well.

**Comment by thekalinga** [comment]
Any chance this be addressed. I've exactly the same issue
```
Could not find com.aries:docker-java-shaded:3.0.14.
```

**Comment by javajon** [comment]
I was getting the error too.  Adding jcenter() fixed it for me.  The clue was from Ben Muschko [found here](https://github.com/bmuschko/gradle-docker-plugin/blob/fd785b7d146a96ae0c570512310bb56ddefbb2b7/README.asciidoc): 

> ATTENTION: as of version 3.2.5 of this plugin we are using the docker-java-shaded library, in favor of docker-java, which itself is hosted on jcenter ONLY.

```
repositories {
    jcenter()
}
```

**Comment by piersf** [comment]
I upgraded today to version 3.2.5 and am getting the same error as well:

```
> Could not find com.aries:docker-java-shaded:3.0.14.
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/aries/docker-java-shaded/3.0.14/docker-java-shaded-3.0.14.pom
         https://repo1.maven.org/maven2/com/aries/docker-java-shaded/3.0.14/docker-java-shaded-3.0.14.jar
```

This is what i have in my build.gradle file:

```
buildscript {
    repositories {
        jcenter()
    }

    dependencies {
        //classpath 'com.bmuschko:gradle-docker-plugin:2.6.8'
        classpath 'com.bmuschko:gradle-docker-plugin:3.2.5'
    }
}

repositories {
    mavenCentral()
}

apply plugin: com.bmuschko.gradle.docker.DockerRemoteApiPlugin

import com.bmuschko.gradle.docker.tasks.container.*
import com.bmuschko.gradle.docker.tasks.image.*
```

@javajon where did you add that section you mentioned in your comment?

@cdancy does the above look wrong to you? Am i missing something here?

Thanks,

**Comment by piersf** [comment]
@cdancy  thank you! That worked!

**Comment by javajon** [comment]
@cdancy - great!, [An example is here](https://github.com/javajon/monitoring-kubernetes/blob/master/microservices/quotes/build.gradle).

**Comment by cdancy** [comment]
Thanks guys. Something is still _not quite_ right, or at least smells fishy, as specifying `jcenter` in the buildscript deps should have been enough. I'll take a look at further look at this and see what I can make of things. Thanks for reporting @piersf

**Comment by javajon** [comment]
@cdancy - Stick with you instinct on smells. I moved my Gradle project from Spring Boot 1.5.x to 2.0.1 and this error popped up "Could not find com.aries:docker-java-shaded:3.0.14.". That lead me to this thread as described by Ben and @abansod. Once I changed from mavenCentral() to jcenter() the error was seemingly resolved and I moved on.

The Kubernetes-client was just needed to get Kubernetes context. I also like its Java/groovy API simplicity.  [gradle-kubernetes-plugin](https://github.com/bmuschko/gradle-kubernetes-plugin) is much needed for those using needing Kubernetes CRUD via Gradle. Ideally much of the CRUD I may want to do may be via Helm. The new Gradle plugin from Wesley Hartford for Helm is great to see [ca.cutterslade.helm](https://plugins.gradle.org/plugin/ca.cutterslade.helm).

**Comment by PoonamGargAgarwal** [comment]
Hi Team , 
I m getting following error with build image 
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':buildImage'.
> Could not resolve all files for configuration ':dockerJava'.
   > Could not find com.aries:docker-java-shaded:3.0.14.
     Required by:
         project :

Please help me to resolve this issue.

**Comment by cdancy** [comment]
@PoonamGargAgarwal that library is hosted on bintray/jcenter so if your gradle build does not have access to it you won't be able to resolve.

**Comment by PoonamGargAgarwal** [comment]
@cdancy I already added jcenter() in repositories . Still it fails during buildimage

**Comment by cdancy** [comment]
@PoonamGargAgarwal can you open a new ISSUE and provide a reproducible snippet?
