### ISSUE TITLE
User document links broken

### ISSUE THREAD

**Issue by liuzy163** [bmuschko/gradle-docker-plugin#632]
The link doesn't work anymore http://bmuschko.github.io/gradle-docker-plugin/docs/groovydoc/com/bmuschko/gradle/docker/tasks/image/DockerPullImage.html. 

Got 404 error.

**Comment by cdancy** [comment]
@bmuschko looks like the recent doc update broke all groovydoc links.

**Comment by bmuschko** [comment]
Thanks for letting us know. I just fixed the issue. Be aware that the path you posted above won't work anymore. Please use the links from the published user guide.

Seems that the GhPages Gradle plugins has trouble with copying content into different subdirectories. Instead of an additive operation is overwrites the existing content. I will report an issue.

**Comment by cdancy** [comment]
@bmuschko thanks for the quick response. It should be noted that a developer that knows I work on this project stopped over yesterday and said something to the effect of: "Hey was just poking around the gradle-docker-plugin and noticed the new docs. Very nice." :)

**Comment by bmuschko** [comment]
@cdancy Great to hear!

**Comment by liuzy163** [comment]
@bmuschko  The problem is still there. If you go to your [published user guide](http://bmuschko.github.io/gradle-docker-plugin/) and click the hyperlink "DockerPullImage" in section 2.3.2 Images table, it leads you to the URL I reported and still gets 404 at this time.

**Comment by bmuschko** [comment]
@liuzy163 WTF! It seems like the GhPages Gradle plugin doesn't work reliably if you use `from`/`into`. However, it seems like it _does_ work if you use it the other way around. It has been corrected.
